### ISSUE TITLE
Crashes in .NET 7 due to ListView private field getting renamed

### ISSUE THREAD

**Issue by BittermanAndy** [FizzcodeSoftware/ObjectListViewRepack#2]
VirtualObjectListView (both the original code, and your repack - thanks for providing it!) fails in .NET 7 when using reflection to set the VirtualListSize.

On line 394 of VirtualObjectListView.cs, it does this:
`var fieldInfo = typeof(ListView).GetField("virtualListSize", BindingFlags.Instance | BindingFlags.NonPublic);`

But that private field has been renamed to `_virtualListSize` in .NET 7:
https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
https://github.com/dotnet/winforms/pull/6627
...so the fieldInfo comes back as null, leading to a NullReferenceException. That NullReferenceException is caught and ignored, so the ObjectListView just shows up as empty.

There may be other places in the code that access the same private field in the same way, I don't know.

I'm not sure of the best way to handle the fix - whether you'll have a separate branch for .NET 7 and later, or whether you'll use #ifdefs in the code - but it needs to search for "_virtualListSize".

**Comment by pauldeboer1987** [comment]
As noted by Jonathan Savage on the sourceforge page 
https://sourceforge.net/p/objectlistview/discussion/812923/thread/d65f06de3b/
using the ListView property "VirtualListSize" instead of as a field, makes this work when used in a dotnet7 application
I've confirmed this continues to work in dotnet 6 as well

**Comment by BittermanAndy** [comment]
Is there any chance the PR @pauldeboer1987 submitted will be accepted and a new release published please?

Or is this package obsolete and I should try to find another ObjectListView repack?

I've been able to stick with .NET 6 as .NET 7 is STS, but .NET 8 is LTS so I will be looking to upgrade.

**Comment by wickedmachinator** [comment]
> Is there any chance the PR @pauldeboer1987 submitted will be accepted and a new release published please?
> 
> Or is this package obsolete and I should try to find another ObjectListView repack?
> 
> I've been able to stick with .NET 6 as .NET 7 is STS, but .NET 8 is LTS so I will be looking to upgrade.

sure, sorry I had no notifications set up for this repo :( publishing ASAP

**Comment by BittermanAndy** [comment]
Fantastic, thank you - a really fast response, between seeing the request and doing it! 🤣 Appreciate it.

**Comment by lilhoser** [comment]
I'm still getting this crash in the nuget package version 2.9.3. Was this published?

```An unhandled exception of type 'System.InvalidOperationException' occurred in System.Windows.Forms.dll
ListView virtualization requires a valid ListViewItem to be provided by the RetrieveVirtualItem event or in the OnRetrieveVirtualItem method.```
